### ISSUE TITLE
Default Year

### ISSUE THREAD

**Issue by aleemb** [yodasw16/date-picker#23]
I had a quick go at the demo and while the dates and months fit on one page, the years are paginated. The initial page that is displayed did not have 2014 and users have to flip to the next page to select it. Would be nice to have the page with the current year show by default.

**Comment by calvinbushor** [comment]
Looking at the module, it looks like the starting year and the ending year is hard coded into the module instead of just using the Date() current year method. If you wanted to submit a pull request modifying the module to not hard code the date, I would be happy to review it. Or, if you want to use it, pull down the module and just look for 2013 and change it to 2014.
